### ISSUE TITLE
Support custom SQL query execution

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#104]
POST Request : 
`/query --> QueryController
`
input payload - use named parameter jdbc template.
named parameters are easy to debug

```
{
   "sql" : "SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEE WHERE ID = :id",
    "params" : {
        "id" : 1
    },
    "single" : true
}
```

The parameter single is optional - it indicates if the query returns 1 result when set to true. Otherwise, by default it returns a list.

**Comment by thadguidry** [comment]
Ensure backtick ` and ' single quote work just fine there (as well as any other special characters.  Which component actually does the validation parsing here for what's between the double-quotes?  And when does that component actually do the checking, what's the sequence actually look like?

**Comment by kdhrubo** [comment]
@thadguidry - can you please share some examples

Mandatory attributes can be checked in the controller.

**Comment by thadguidry** [comment]
Just search for "sql string literals".
https://stackoverflow.com/a/11321508
https://dev.mysql.com/doc/refman/8.2/en/string-literals.html
Where the whole structure for MySQL is here: https://dev.mysql.com/doc/refman/8.2/en/language-structure.html

**Comment by thadguidry** [comment]
And over the years, as UTF-8 needed to be supported fully...many things changed and were deprecated.  For example, in MySQL:
> Use of the dollar sign as the first character in the unquoted name of a database, table, view, column, stored program, or alias is deprecated, including such names used with qualifiers (see [Section 9.2.2, “Identifier Qualifiers”](https://dev.mysql.com/doc/refman/8.2/en/identifier-qualifiers.html)). An unquoted identifier beginning with a dollar sign cannot contain any additional dollar sign characters. Otherwise, the leading dollar sign is permitted but triggers a deprecation warning.

**Comment by thadguidry** [comment]
There's a Java library that does validation stuff and I think Tony used it for the Database extension in OpenRefine, if I recall.  Need me to find it?

**Comment by kdhrubo** [comment]
Let the database perform these validations, DB2Rest in this case just acts as facilitator.

**Comment by souravroy** [comment]
@kdhrubo Could you please review following PR ?
https://github.com/kdhrubo/db2rest/pull/156

**Comment by kdhrubo** [comment]
@souravroy closing this ticket.
