### ISSUE TITLE
Trim or replace SQL test files

### ISSUE THREAD

**Issue by thadguidry** [kdhrubo/db2rest#142]
Our project shows it's not a Java project but more so a PLsql project because of the large db testing resources (large .sql scripts with many records in them).
We should trim the records to only a handful (like 10 records) in the test files.

**Comment by kdhrubo** [comment]
Please source the test files from this repo

https://github.com/jOOQ/sakila

**Comment by kdhrubo** [comment]
@souravroy @bharath8121 - @thadguidry - this issue resolved now ?

**Comment by thadguidry** [comment]
@kdhrubo Indeed the SQL files are trimmed.  And our project shows up in GitHub as a Java project.

**Comment by kdhrubo** [comment]
Will close this issue if no further action is required.

**Comment by souravroy** [comment]
Hi @kdhrubo, @thadguidry  SQL test files have been trimmed. It loads mainly following tables:
`actor, category, film, film_actor, film_category, language`

These tables maintain primary key, foreign key constraints, indexes etc.

Each table contains 4 records only.

**Comment by kdhrubo** [comment]
Close the issue.
