### ISSUE TITLE
Add the ability to specify column names to include during insert

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#155]
Example: 

```
POST /film?columns=title,release_year

{
  "title": "Natural Disaster Prevention and Control",
  "release_year": "2015-09-11",
  "duration": 110,
  "genre": "Comedy",
  
}
```

In the example above 'duration', and 'genre' attributes will be ignored in the insert. 

**Hints**

Copy to a new Map, if columns request parameter is present with column names, if columns parameter is present and is blank
it is ignored.

**Comment by souravroy** [comment]
Create a separate ticket for bulk insert:
https://github.com/kdhrubo/db2rest/issues/242

**Comment by souravroy** [comment]
@kdhrubo I'm currently working on this ticket

**Comment by souravroy** [comment]
If columns is present that means we just need to execute an insert with those 2 columns only from the 4 that are in the payload.
Someone might have got an extract with many columns but created a table with a less no of columns for loading/analysis.
This is only applicable when columns request param is present you need to recreate the incoming data map
If a column is present in columns req param but not in payload , ensure that  is included and let db deal with it as null

**Comment by souravroy** [comment]
https://github.com/kdhrubo/db2rest/pull/248 is merged
