### ISSUE TITLE
Experimental - Use ANTLR to parse RQL projection and identify the columns and tables

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#165]
A select request parameter specifies the columns to retrieve from the result of an SQL query. It can look like 

`http://localhost:8080/film?select=film_id:id,title,description,release_year:yearOfRelease;language(language_id,name)&filter=release_year==2006&page=2&size=10&sort=title`

The following columns and tables are retrieved

|Table                 |Column                     |
|---------------|--------------------|
|film                   | film_id as id             |
|film                   | title                           |
|film                   | description              |
|film                   | release_year            |
|language         | language_id             |
|language         | name                         |

**Comment by thadguidry** [comment]
umm, but you applied an alias to the `release_year` column as `yearOfRelease` ?  and then filtered by `release_year` ?  or did you typo on the column name?

**Comment by kdhrubo** [comment]
Alias is only for projection.

Selection should always use the actual column name because the alias is not known to the database or cannot be used in where. 

This is not an error condition.

**Comment by thadguidry** [comment]
OK, but alias is allowed in where conditions in SQL.  So this is some limit in some library or something is what I guess you are actually trying to tell me.
