### ISSUE TITLE
Add support for mariadb

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#175]
**Acceptance**

1. All the integration tests are completed for MariaDB - similar to MySQL and PostgreSQL
2. All tests must pass

**Comment by thadguidry** [comment]
I'd rather not encourage this piece of shit software.

**Comment by kdhrubo** [comment]
For us it's just writing the integration tests. Nothing special code required.

**Comment by thadguidry** [comment]
Sto terra mea

**Comment by adityakukankar** [comment]
Hi @kdhrubo, I can work on this issue if no one is working on it. Could you please assign it to me?

**Comment by kdhrubo** [comment]
go ahead fork it. Follow the test cases for mysql. You need docker locally because integration tests makes use of testcontainer. Also dont forget to star the project.

**Comment by kdhrubo** [comment]
@adityakukankar - assigned - let me know if you would work on this. 

You will need to implement the integration tests.

**Comment by kdhrubo** [comment]
@adityakukankar - great job. This can be closed now.
