### ISSUE TITLE
Add support for mongodb

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#176]

**Comment by thadguidry** [comment]
NO.  Let's close this issue.
https://restheart.org/

**Comment by thadguidry** [comment]
or more properly describe what we want to accomplish perhaps in a "user story" sentence or two.
Maybe an integration WITH RESTHeart is something feasible, but then what are we solving or making better, simpler, etc.
Need a user story here on this issue.

**Comment by kdhrubo** [comment]
Essentially transpile the same rSQL and convert to Mongodb filters..may be no joins.

**Comment by kdhrubo** [comment]
Duplicate #315
