### ISSUE TITLE
Add support for Oracle

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#178]
Follow the other integration test patterns for MySQL and PostgreSQL. 
Use Oracle test container support.

**Comment by lingaiahdanda** [comment]
@kdhrubo  I will start working on this. I will be taking sometime to understand the project.

**Comment by lingaiahdanda** [comment]
@kdhrubo 

Update about the work on writing integrated tests

1/28/2024 - created the schemas , tables, procedure and functions for testing. Need to verify the syntaxes are correct.

**Comment by kdhrubo** [comment]
Did you create the same sakiladb for oracle ?

We use a trimmed version from the JOOQ repo

**Comment by MichalisDBA** [comment]
Please allow the use of different oracle jdbc drivers versions (for example `ojdbc6-11.2.0.4.jar`) so we can create APIs for legacy Oracle Databases.

**Comment by kdhrubo** [comment]
Which versions of Oracle do you want us to support ? We can definitely look into supporting legacy oracle databases.

**Comment by MichalisDBA** [comment]
Oracle 9i. We use another java based tool `ReplicaDB` and we swapped the jdbc drivers to support Oracle 9i and works flawless.
https://github.com/osalvador/ReplicaDB/issues/61#issuecomment-1055169183

This is the compatible driver

https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc6/11.2.0.4/ojdbc6-11.2.0.4.jar

**Comment by kdhrubo** [comment]
Got it. Have you tried using the current version? 
The challenge is testing. We use testcontainer for integration test - which does not have oracle9i support. 

Also we do not have access to oracle 9i or other versions. If you help us we can definitely make this compatible with Oracle 9i. 

You can also join us on discord for faster response.

**Comment by MichalisDBA** [comment]
I haven't tried it yet. Will report at the start of the week. I can not join discord. It says "This invite may be expired"

**Comment by kdhrubo** [comment]
Super. 

Here is the updated invite -[]( https://discord.gg/EeSQHT3w)

**Comment by kdhrubo** [comment]
@lingaiahdanda - closing this as already implemented now. 

Duplicate of 

#386
