### ISSUE TITLE
Exists query support

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#182]
- Support filter, join. 
- Ignore select fields - always do select 1 
- add limit of 1 row 

if a row exists then return true.

```
select 1
from 
        film
where 
        year_of_release = 2024
limit 1
```

Spring JDBC might throw an exception if no row is returned. Please keep this in consideration.

**Comment by ntananh** [comment]
To be clear, is the following example consistent with what we expect: 

Query:

`/film?select=film_id,title,description&filter=review=exists=(rating==5)`

This will be translated to:

```
SELECT film_id, title, description 
FROM film
WHERE EXISTS (
	SELECT 1
	FROM review
	WHERE rating = 5
	LIMIT 1
)
```

**Comment by kdhrubo** [comment]
The goal of this endpoint is to check if a record exists for the given conditions. It will return a `true` or `false` to indicate if the row exists. This is similar to the Spring DATA JPA `exists` query. 

I missed this in the initial description. The endpoint should be similar to `count`

`/{tableName}/exists`

In the above example - the `select` request parameter will be ignored. 

`/film_review/exists?filter=rating=eq=5`

```
SELECT 1
	FROM film_review
	WHERE rating = 5
	LIMIT 1
```
