### ISSUE TITLE
Return generated keys for insert

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#183]

**Comment by ntananh** [comment]
Hi @kdhrubo,  I'm really interested in db2rest project. Could I work on this issue?

**Comment by kdhrubo** [comment]
Yes absolutely you are welcome 🤗. Please go ahead.

**Comment by ntananh** [comment]
Hi @kdhrubo, do we expect that insert action return data like this

```
{
    "rows": 1,
    "generated_keys": 2
}
```

Or we change response data to return generated_keys only:

```
{
    "generated_keys": 2
}
```

**Comment by kdhrubo** [comment]
Let's return both.

For bulk insert this will be a row of keys

**Comment by kdhrubo** [comment]
@ntananh you have done a fantastic job with this one. 

Whats the best way to contact you and add you to slack.

**Comment by ntananh** [comment]
Hi @kdhrubo, Thank you =))

About Slack, can I use my email: tananh691@gmail.com

**Comment by kdhrubo** [comment]
Please check your email you should have 2 requests. Then I will delete this messages to not make your email public @ntananh
