### ISSUE TITLE
Add support for GZIP compression for response

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#243]
https://dev.to/jackynote/supercharge-your-spring-boot-rest-api-with-gzip-compression-1a66

https://howtodoinjava.com/spring-boot/response-gzip-compression/

**Comment by drzeb** [comment]
Hi @kdhrubo GE
I would like to give it a try. Please let me know if it is ok.

**Comment by kdhrubo** [comment]
Yes go ahead and dont forget to star the project :)

**Comment by drzeb** [comment]
Hi @kdhrubo GE
Do we have some payload for this application?

**Comment by kdhrubo** [comment]
What do you mean ?

**Comment by drzeb** [comment]
Like some postman collection to hit the end points

**Comment by kdhrubo** [comment]
There is no fixed set of endpoints. The endpoints are driven by tables in yr database. So pls create 1-2 tables and follow the documentation on the website

**Comment by kdhrubo** [comment]
@drzeb - is this done?

**Comment by drzeb** [comment]
Probably done with the issue, need to test it. I am so sorry got super busy with job. I will devote some time this weekend.

**Comment by kdhrubo** [comment]
No worries..take yr time

**Comment by Praneethct** [comment]
Hello Dhrubo, should i enable compression for every controller or just add the dependencies for this issue?

**Comment by kdhrubo** [comment]
See the links above. It's a configuration you need to turn on for entire app.
