### ISSUE TITLE
Organize static test data into subfolders and instead use JSON with a Reader Util class

### ISSUE THREAD

**Issue by thadguidry** [kdhrubo/db2rest#268]
Mentioned in previous PR comment here:
>This is static data (almost module like). And looks like only data for Films, so I'd likely rename this to something like `/RequestFilmData.java`
>
>Collaborator
>@[thadguidry](https://github.com/thadguidry) thadguidry [5 minutes ago](https://github.com/kdhrubo/db2rest/pull/267#discussion_r1485404285)
and instead of a path like `src/test/java/com/homihq/db2rest/utils/ITestUtil.java` perhaps be named and moved to a concise path of `src/test/data/RequestFilmData.java`

1. We want to reorganize the folder structure for Tests and particularly for Test Resources and Static Test Data.
2. We could use JSON for holding static test data in a `/test/resources/data` and have a util class under `/test/resources/util` for `ReadTestDataJson.java` or whatever.  The JSON data file could be under that `/test/resources/data` subfolder and named `RequestFilm.json` as an example.

**Comment by souravroy** [comment]
@thadguidry that is correct. We may not need any Util class. We can load test json files from `/test/resources/data` subfolder as a Resource and use it in our integration tests

**Comment by kdhrubo** [comment]
This issue is partially resolved. All the necessary actions have been taken. However, not all classes have been cleaned up. 
Hence adding label.
