### ISSUE TITLE
Ambiguous wording for TSID design

### ISSUE THREAD

**Issue by thadguidry** [kdhrubo/db2rest#282]
In [`/design/insert.md`](https://github.com/kdhrubo/db2rest/blob/master/design/insert.md)

> 1. Construct INSERT columns with the key set of the incoming data object.
> 2. If includeColumns is specified then use those instead of 1.
> 3. If a column with default value is not included in 1 or 2 above then it will be set to the default value by the database.
> 4. If tsIdEnabed = true, then find the primary key columns.
>    - detect the data type - if integer type, set a numeric TSID.
>    - if the data type is string - set string type TSID.
>    - add these columns in the data.

That last bullet is confusing to me.  "add these columns in the data"
WHICH columns to add?  The primary key columns?  or the key columns from the incoming data object from 1?
Maybe re-word that last bullet for clarity.

**Comment by kdhrubo** [comment]
tsid is only applicable for the primary key columns. Step4 is only works with PK columns as stated in the first line.
