### ISSUE TITLE
Document the minimum requirements for DB2REST to run in README

### ISSUE THREAD

**Issue by thadguidry** [kdhrubo/db2rest#283]
We should put a #Requirements section in the README.
And detail the minimum requirements for DB2REST to run and serve as a gateway and provided API services for 1 db connection.

For that case, I "think" the only requirements are:
1. 2 GB RAM  (based on a minimum Spring boot stack, I think?)
2. JRE Java 17 or greater (based on our POM's declaration of minimum java version of 21 to compile, but backwards compatible for 17 to run I think since we don't use special stuff?)
3. anything else?

**Comment by kdhrubo** [comment]
@thadguidry 

Updated

https://db2rest.com/docs/run-db2rest-on-docker/
https://db2rest.com/docs/intro

**Comment by kdhrubo** [comment]
@thadguidry please review to close this issue.

**Comment by thadguidry** [comment]
Lgtm

Thad Guidry
________________________________
