### ISSUE TITLE
Change banner 

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#354]
The new banner should contain
1. Application name - db2rest in ASCII colored 
2. db2rest version
3. Spring Boot version.
4. db2rest website

**Comment by adityakukankar** [comment]
Hi @kdhrubo, did the changes for the banner. Let me know if there is any changes needed.
![db2rest](https://github.com/kdhrubo/db2rest/assets/25963376/8ed563c2-1cb9-40a6-9a6a-5bc381892fab)

**Comment by thadguidry** [comment]
Let's remove those green double colons and instead have a single one 

```
|  db2rest version  :       v0.2.2-RC4         |
|  Spring-Boot version  :   v3.2.3             |
|  Visit website  :   [https://db2rest.com/]   |
```

**Comment by kdhrubo** [comment]
good start @adityakukankar
