### ISSUE TITLE
Define default fetch limit option

### ISSUE THREAD

**Issue by MichalisDBA** [kdhrubo/db2rest#379]
Have an option to define (env variable) the default fetch limit (for example 1000 records) so that API calls to large tables without the LIMIT parameter do not abuse and stress the database and network.

To overwrite it on API call, do something like `/endpoint/?limit=none`

**Comment by kdhrubo** [comment]
Good point.
There is support for limit and offset. 
[https://db2rest.com/docs/read/handle-large-resultsets-with-pagination](https://db2rest.com/docs/read/handle-large-resultsets-with-pagination
)Will add the default LIMIT and the opt out parameter.

**Comment by kdhrubo** [comment]
Will update docs here it how it works

- if no limit is set default now set to 100. 
- default can be altered with parameter DEFAULT_FETCH_LIMIT
- did not introduce any new request parameter
- if there is need to ignore DEFAULT_FETCH_LIMIT, set request parameter limit=0

**Comment by sanchezcarlosjr** [comment]
The docs and this comment are wrong.
>     * if there is need to ignore DEFAULT_FETCH_LIMIT, set request parameter limit=0

From your code, https://github.com/9tigerio/db2rest/blob/ac362eb8ecc2ccb9a41604ddbdd3821f057cd1ac/src/main/java/com/homihq/db2rest/jdbc/sql/SqlCreatorTemplate.java#L135, I can deduce any number less than -1 would ignore the limit constructor. Then, I tested ```limit=-2```, and it worked.

```
        if(readContext.getLimit() > -1) data.put("limit", readContext.getLimit());
        if(readContext.getLimit() == -1) data.put("limit", db2RestConfigProperties.getDefaultFetchLimit());
```

**Comment by thadguidry** [comment]
Looking forward to your PR @sanchezcarlosjr in our docs repo https://github.com/9tigerio/db2rest-web
