### ISSUE TITLE
Oracle - ORA-00920: invalid relational operator

### ISSUE THREAD

**Issue by MichalisDBA** [kdhrubo/db2rest#437]
Hello.

The operators below do not work and produce the `ORA-00920: invalid relational operator` error

```
<
=lt=
<=
=le=
=in=
=out=
=startWith=
=endWith=
```

**Comment by kdhrubo** [comment]
Linked issues
#337 
#338

**Comment by kdhrubo** [comment]
Starting manual testing for oracle 9i

**Comment by kdhrubo** [comment]
Oracle 9i manually tested and looks good. @MichalisDBA - pls test and let us know of any issues. Then we can close this issue. 

You can download the release candidate versions from links below:

[https://download.db2rest.com/db2rest-oracle9i-0.2.7-RC1.jar](https://download.db2rest.com/db2rest-oracle9i-0.2.7-RC1.jar)

[https://download.db2rest.com/db2rest-0.2.7-RC1.jar](https://download.db2rest.com/db2rest-0.2.7-RC1.jar)

**Comment by MichalisDBA** [comment]
Hello @kdhrubo . It is working now fine. Please edit your docs, there is a typo in greater than or equal

![image](https://github.com/kdhrubo/db2rest/assets/68512501/af7f9b79-59cd-4502-86c7-70264d72b8a6)

Instead of `=gt=` to `=ge=`

Thanks.

**Comment by kdhrubo** [comment]
Closing this issue now.
