### ISSUE TITLE
MySQL - You have an error in your SQL syntax - Operators

### ISSUE THREAD

**Issue by MichalisDBA** [kdhrubo/db2rest#438]
Hello.

Same error as Oracle https://github.com/kdhrubo/db2rest/issues/437

The operators below do not work and produce a `You have an error in your SQL syntax; check the manual that corresponds to your...` error

```
<
=lt=
<=
=le=
=in=
=out=
=startWith=
=endWith=
```

**Comment by kdhrubo** [comment]
Fixed greater than

`/film?filter=rental_duration>6`

`/film?filter=rental_duration=gt=4`

**Comment by kdhrubo** [comment]
Fixed greater than equal to


`/film?filter=rental_duration>=6`

`film?filter=rental_duration=ge=6`

**Comment by kdhrubo** [comment]
Fixed less than 

`/film?filter=rental_duration=lt=4`

`/film?filter=rental_duration<4`

**Comment by kdhrubo** [comment]
Fixed less than equal to

`/film?filter=rental_duration=le=3`

`/film?filter=rental_duration<=3`

**Comment by kdhrubo** [comment]
Fixed  IN

`/film?filter=film_id=in=(1,2,3)`

`/film?filter=rating=in=(PG,G,NC-17)`

**Comment by kdhrubo** [comment]
Fixed OUT

`/film?filter=film_id=out=(1,2,3)`

`/film?filter=rating=out=(PG,G,NC-17)`

**Comment by kdhrubo** [comment]
FIXED START WITH n END WITH

`/film?filter=title=endWith=EASY`

`/film?filter=title=startWith=BASIC`
