### ISSUE TITLE
MongoDB - Add findAll operation

### ISSUE THREAD

**Issue by souravroy** [kdhrubo/db2rest#447]

**Comment by thadguidry** [comment]
In Search operations, there are typically 2 approaches of "finding things"... that of a `match` condition and that of a `find` condition.  Where `match` attempts to match a string in its entirety against a pattern and outputs an array of all capturing groups.  And `find` returns an array of substrings inside a system or another string that matches a pattern.  Both have their uses but output differently.  https://docs.oracle.com/javase/tutorial/essential/regex/matcher.html

@souravroy What implementation details are you asking for with this issue?  Can you describe your motivations in your original comment?

**Comment by kdhrubo** [comment]
@thadguidry - this is mongodb version of the query that has been implemented for RDBMS. 
Findall - input are RSQL filter and other pagination parameters.

**Comment by thadguidry** [comment]
@kdhrubo Can you point me to the implementation for my review please?

**Comment by kdhrubo** [comment]
https://github.com/kdhrubo/db2rest/blob/master/src/main/java/com/homihq/db2rest/jdbc/rest/read/ReadController.java

https://github.com/kdhrubo/db2rest/blob/master/src/main/java/com/homihq/db2rest/jdbc/service/JdbcReadService.java

**Comment by souravroy** [comment]
I've to integrate RSQL as part of this change, as I need to add filters
https://github.com/kdhrubo/db2rest/issues/315

**Comment by souravroy** [comment]
PR# https://github.com/kdhrubo/db2rest/pull/465

**Comment by kdhrubo** [comment]
PR is merged hence closing this issue.
