### ISSUE TITLE
Version db2rest-oracle9i-0.2.7-RC1.jar hangs at Fetching all schema meta data

### ISSUE THREAD

**Issue by MichalisDBA** [kdhrubo/db2rest#450]
Hello. In latest version `db2rest-oracle9i-0.2.7-RC1.jar` if you do not specify the `-DINCLUDE_SCHEMAS` parameter, the application hangs at `Fetching all schema meta data.`. This was not happening in previous version.

**Comment by kdhrubo** [comment]
Investigated it - schema has many tables and loads of columns. When no exclusion is applied it scans through all including system tables and columns. Eventually you will see after several minutes it does timeout. Loading column details is slow. 

It can be optimized by 
a. excluding system tables. For each database product a list will be maintained. 
b. column details will be loaded in parallel. 

Will make this part of  0.2.8 release in a couple of weeks.

**Comment by MichalisDBA** [comment]
Latest version 0.2.8 fixed it. Still a bit slow when you have many tables under a schema but it loads fine at the end. Thank you.

**Comment by thadguidry** [comment]
@kdhrubo I wonder if the slowness is due to cache building? or problems therein?

**Comment by MichalisDBA** [comment]
@thadguidry It took 10 minutes to load a schema with 53 tables and 3905 views.

**Comment by kdhrubo** [comment]
Yes it's building cache. I will investigate further.

**Comment by kdhrubo** [comment]
Closing #460 discussion added for future review.
