### ISSUE TITLE
Bug with OR, AND RSQL operators

### ISSUE THREAD

**Issue by MichalisDBA** [kdhrubo/db2rest#451]
Hello. Let's say we have a table `TEST_RANGE` with these values

```
[
	{
		"ID": 1,
		"NAME": "aaa"
	},
	{
		"ID": 2,
		"NAME": "bbb"
	},
	{
		"ID": 3,
		"NAME": "ccc"
	},
	{
		"ID": 4,
		"NAME": "ddd"
	},
	{
		"ID": 5,
		"NAME": "eee"
	},
	{
		"ID": 6,
		"NAME": "ffff"
	},
	{
		"ID": 7,
		"NAME": "ggg"
	},
	{
		"ID": 8,
		"NAME": "hhh"
	},
	{
		"ID": 9,
		"NAME": "iii"
	},
	{
		"ID": 10,
		"NAME": "jjj"
	}
]
```

If we want to construct a query that get's the range between IDs 5 and 7 we do it like this

`/TEST_RANGE?filter=ID>=5;ID<=7`

The problem is that the endpoint returns the wrong result

```
[
	{
		"ID": 7,
		"NAME": "ggg"
	}
]
```

From the DEBUG log the query that shows is being executed is 

```
Executing prepared SQL statement:
[SELECT
    TEST_82.ID
    ,TEST_82.NAME
FROM
    testos.TEST_RANGE TEST_82
WHERE
    ( TEST_82.ID >= ? AND TEST_82.ID <= ? )
LIMIT 100
]
```

If you run this directly with an SQL IDE

```
SELECT
    TEST_82.ID
    ,TEST_82.NAME
FROM
    testos.TEST_RANGE TEST_82
WHERE
    ( TEST_82.ID >= 5 AND TEST_82.ID <= 7 )
LIMIT 100
```

the result will be

```
ID	NAME
5	eee
6	fff
7	ggg
```

Same bug happend if you use the `OR` operator.

`/TEST_RANGE?filter=ID==5,ID==7`

The endpoint returns

```
[
	{
		"ID": 7,
		"NAME": "ggg"
	}
]
```

The sql statement from the DEBUG log is

```
Executing prepared SQL statement
[SELECT
    TEST_82.ID
    ,TEST_82.NAME
FROM
    testos.TEST_RANGE TEST_82
WHERE
    ( TEST_82.ID = ? OR TEST_82.ID = ? )
LIMIT 100
]
```

If you run this directly to an SQL IDE

```
SELECT
    TEST_82.ID
    ,TEST_82.NAME
FROM
    testos.TEST_RANGE TEST_82
WHERE
    ( TEST_82.ID = 5 OR TEST_82.ID = 7 )
LIMIT 100
```

The result is

```
ID	NAME
5	eee
7	ggg
```

Another example

`/TEST_RANGE?filter=ID>=5,ID==7`

The endpoint returns

```
[
	{
		"ID": 7,
		"NAME": "ggg"
	},
	{
		"ID": 8,
		"NAME": "hhh"
	},
	{
		"ID": 9,
		"NAME": "iii"
	},
	{
		"ID": 10,
		"NAME": "jjj"
	}
]
```

Clearly missing `ID = 5` and `ID = 6`

The sql query from the request

```
Executing prepared SQL statement
[SELECT
    TEST_41.ID
    ,TEST_41.NAME
FROM
    testos.TEST_RANGE TEST_41
WHERE
    ( TEST_41.ID >= ? OR TEST_41.ID = ? )
LIMIT 100
]
```

If you run it with an SQL IDE

```
SELECT
    TEST_41.ID
    ,TEST_41.NAME
FROM
    testos.TEST_RANGE TEST_41
WHERE
    ( TEST_41.ID >= 5 OR TEST_41.ID = 7 )
LIMIT 100
```

Result

```
ID	NAME
5	eee
6	fff
7	ggg
8	hhh
9	iii
10	jjj
```

Tried on Oracle and MySQL databases.

**Comment by MichalisDBA** [comment]
Tried with latest version 0.2.8. Everything works fine now. The correct results are returned. Thank you!

**Comment by thadguidry** [comment]
@MichalisDBA Awesomely good news!  Thanks for the feedback!  Closing now.  Keep those issues coming when you spot something odd!
