### ISSUE TITLE
Cannot filter /schema/objects endpoint

### ISSUE THREAD

**Issue by MichalisDBA** [kdhrubo/db2rest#456]
Can not filter `/schema/objects` endpoint to search for specific schemas, tables, views.

`/schema/objects?filter=schema==`
`/schema/objects?filter=name==`
`/schema/objects?filter=type==`

**Comment by thadguidry** [comment]
Hi @MichalisDBA is this where you want to expose schema objects in your application?  Was this so you can expose in a selector some categories or particular domains to your app users?  Or did you have some other uses in mind of schema selection in your application you are building with DB2Rest?

**Comment by MichalisDBA** [comment]
Hi @thadguidry maybe would be better to be configurabled via env variables the schema/objects path.
My use case is to see what objects are loaded and available to me so i can query them.

That way i can give a user a single endpoint that he can see what objects are available to him to query instead of maintaining a list for every user of what he can query.

**Comment by thadguidry** [comment]
Righto.  OK.  Hmm, isn't there a nice custom SQL expression to use instead for this with Oracle where you can query the USER_OBJECTS view?  I know I can do this easily in PostgreSQL.
Sorry, but I've long forgotten my Oracle skills and the differences between between stupid things like `local user` and `common user` etc.

Regardless, this https://docs.oracle.com/en/database/oracle/oracle-database/23/admin/managing-schema-objects.html#GUID-827749E0-E67C-44DB-ABA4-2596167F2EAE  in section 17.13 does seem to resonate with this issue.  Perhaps custom query to return ALL_OBJECTS or USER_OBJECTS views?

Let me know.

**Comment by thadguidry** [comment]
We "could" in theory more easily expose this through the API via something that might look like:

```
http://localhost:8080/?objectsOwned
http://localhost:8080/?objectsAll
```
or maybe `/user?objectsOwned` ?  Wait NO, that syntax would be asking for the `user` table and a query parameter ... hmm.  We need to come up with some good syntax for doing schema queries easily, while keeping our `/<table>?` convention.  Maybe some keyword before the `/` ? or special parameter keywords directly after the `/` as my examples above? 

@dhrubo ?

**Comment by kdhrubo** [comment]
JDBC meta data builder queries these tables under the hood. Because the driver is implemented by the database vendor.

**Comment by kdhrubo** [comment]
Will add filters in 0.2.9 😁

**Comment by thadguidry** [comment]
well, the problem with that endpoint is that...
- In PostgreSQL and others, you can actually have a table name called "schema".  So that endpoint convention sorta breaks our syntax convention.  You cannot have objects prefixed with `pg_` however as they are reserved for system schemas.  DB's have lots of reserved names and differ by vendor.

@kdhrubo Not so sure about an endpoint named like that?

**Comment by kdhrubo** [comment]
If a table named schema is present in user schema it will be cached and returned by this query.

**Comment by kdhrubo** [comment]
This endpoint ends with `/objects` so the MVC controller will use this one when the query is for db objects

When you want to view the records of the schema table then that endpoint does not end with `/objects`. This is how we can differentiate. Similar to the `join` syntax. 

I am not sure what query the JDBC driver actually runs under the hood.

**Comment by thadguidry** [comment]
@kdhrubo I understand that.  But that's like saying your sub-collection is dictating the actual real collection.  But I am saying that it is not the way to do it properly at all.  It actually breaks the REST best practices with Nesting to show Relationships between Sub-collection Resources, as well as noun pluralization for Collection Resources.

/posts/author
/posts/postId/comments
/schema
/schemas
/schemas/objects

We are doing it Non-RESTful then.
https://restfulapi.net/resource-naming/ 
https://www.javaguides.net/2018/06/restful-api-design-best-practices.html

And I don't really like that or appreciate that we break many RESTful best practices.

**Comment by kdhrubo** [comment]
Not really it's very common to use command or controller pattern for such scenarios.

If you can suggest a better name for this end point we can make changes.

**Comment by thadguidry** [comment]
It's very common that 1000's of developers do it WRONG.  I absolutely know that.  It's a common misunderstanding that gets abused in command and controller patterns because of lack of knowledge of RESTful Collection Naming conventions.  We're the experts here and should stick to correct conventions of industry norms.

I'd suggest that we stick to our original plan of the first Collection to always be the `<table name>`.
I'd further suggest that when we don't care about dealing with Tables as the first Collection default resource, but instead system commands, that we can adopt a prefix convention such as `$`:
```
http://localhost:8080/$schema
http://localhost:8080/$version
http://localhost:8080/$help
etc...
```

This is like saying, give me the resource document for schema, version, help, etc.
When there is no document prefix, then we treat that first Collection resource as a `<table name>`

Google does this sorta thing for their API's, for example, play around
```
https://eventarc.googleapis.com/$discovery/rest?version=v1
https://eventarc.googleapis.com/$discovery
```

**Comment by kdhrubo** [comment]
Makes sense..we can adopt the $ pattern.

Can you pls review the join syntax and recommend there (a separate issue please) 🥺

**Comment by kdhrubo** [comment]
![image](https://github.com/kdhrubo/db2rest/assets/1124292/efb7ec47-93df-4719-84e8-edd839f692af)

**Comment by kdhrubo** [comment]
![image](https://github.com/kdhrubo/db2rest/assets/1124292/ebfdfd25-4afe-4b26-8850-46abde720a8e)

**Comment by kdhrubo** [comment]
Filter by schema name (like search on schema cache)

![image](https://github.com/kdhrubo/db2rest/assets/1124292/9eaeead5-6306-4561-a4a1-a7bac7a10e5b)

**Comment by kdhrubo** [comment]
![image](https://github.com/kdhrubo/db2rest/assets/1124292/aed8ae7e-f5e9-4418-9268-eed9ebd49eab)

**Comment by kdhrubo** [comment]
Search by type = `table`

![image](https://github.com/kdhrubo/db2rest/assets/1124292/de949351-7e4a-4d29-b5dc-2ee9a623c8a1)


Search by type = `view`

![image](https://github.com/kdhrubo/db2rest/assets/1124292/14cce95f-81a6-4cd3-8b4b-0fa8aa0cd33c)

**Comment by kdhrubo** [comment]
Will be available in 0.2.9 release

**Comment by kdhrubo** [comment]
@MichalisDBA - please share your feedback on this issue. let us know if it can be closed.

**Comment by MichalisDBA** [comment]
@kdhrubo

Yes it is working fine. Just mentioned in the docs that to search for a table you have to use `$schemas?filter=name==search` and not use `=like=` operator.

**Comment by kdhrubo** [comment]
Closing follow up here - 
https://github.com/kdhrubo/db2rest-web/issues/45
