### ISSUE TITLE
Oracle 9i - ORA-00923 Error

### ISSUE THREAD

**Issue by MichalisDBA** [kdhrubo/db2rest#489]
Hello.

Some times there are tables and views with bad column naming. For example this one table schema:

```
CREATE TABLE DB2REST.TEST_BAD_COLUMNS
(
  ID                         INTEGER,
  NAME                       VARCHAR2(50 BYTE),
  "Bad Varchar Column Name"  VARCHAR2(50 BYTE),
  "Bad Int Column Name"      INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;
```

When you have such tables or views and you try to get them via the API, it throws an error:

```
{
	"type": "https://github.com/kdhrubo/db2rest/generic-error",
	"title": "Generic Data Access Error",
	"status": 400,
	"detail": "ORA-00923: FROM keyword not found where expected\n",
	"instance": "/TEST_BAD_COLUMNS",
	"errorCategory": "Data-access-error",
	"timestamp": "2024-04-16T14:05:12.952434229Z"
}
```

This is because the query db2rest tries to run in the database is like that:

```
SELECT * FROM (
    SELECT
        TEST_74.ID
        ,TEST_74.NAME
        ,TEST_74.Bad Varchar Column Name
        ,TEST_74.Bad Int Column Name
    FROM
        DB2REST.TEST_BAD_COLUMNS TEST_74



)
WHERE ROWNUM <= 100
```

For these cases the bad column names must be quoted like this to run successfully the query:

```
SELECT * FROM (
    SELECT
        TEST_74.ID
        ,TEST_74.NAME
        ,TEST_74."Bad Varchar Column Name"
        ,TEST_74."Bad Int Column Name"
    FROM
        DB2REST.TEST_BAD_COLUMNS TEST_74



)
WHERE ROWNUM <= 100
```

**Comment by thadguidry** [comment]
@kdhrubo I would hope we are always creating SQL SELECT statements that are always double quoting column names?  And simply inform (document) that we pass along quoted column names, and so column names will always be recognized as case sensitive.  What do you think?  Although creation of objects because more strict as well if double quotes are used for their creation.

**Comment by kdhrubo** [comment]
Actually there is no use of double quotes in column names ?
Is it suitable for all databases ?

**Comment by kdhrubo** [comment]
So for all db column names and table names should be in quotes ?

**Comment by thadguidry** [comment]
delimited identifiers - delimited meaning they have a token at their start and end.  Typically a " double quote.

**Comment by thadguidry** [comment]
yes, the only special case that comes up is with Unicode.
PostgreSQL has the `U&` prefix before the delimited identifier.  So, 
```sql
SELECT U&"\0441\043B\043E\043D" FROM my_table
```

**Comment by grabdoc** [comment]
Double quotes wont work for mysql its back tick.

**Comment by MichalisDBA** [comment]
Can confirm. Latest version 0.3.0 is working fine. 

Have in mind for Microsoft SQL server, when you support it, i think the default way to escape column names are by using the square brackets like this `[column name]`
