### ISSUE TITLE
New SSL Factory required to handle SSL certificates on cloud platforms

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#494]

**Comment by thadguidry** [comment]
@kdhrubo but why did you keep the "SingleCert" in the classname when it can deal with more?  Hmm, should be "SingleFileCert"?  1 file can have multiple certs as we know now.

**Comment by kdhrubo** [comment]
Same class can be used to load from 1 file which has one cert (kinda 2)
