### ISSUE TITLE
Add Parameter type for custom query

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#579]

**Comment by lserveriiev** [comment]
Hey @kdhrubo! I can pick up the task. Could you give some details?

**Comment by kdhrubo** [comment]
@lserveriiev - hi story is redundant now that we have removed support for custom query for upcoming release. 
We have started work on parameterized query instead.

There are other issue to support Microsoft SQL server. Please let me know if you would be interested in working on that one. That one should be a nice good start.

**Comment by lserveriiev** [comment]
Hey @kdhrubo, ok, I can pick up the feature.

There are some implementation details from my point of view:
1. Create a new `mssql-dialect` dialect. Have a look at the existing dialects. At first glance, it should look like the `MySQLDialect`.
2. Add new integration tests for the new dialect into `api-rest` module.

Do you have something to add? Or I can pick up less time-consuming tasks.

**Comment by kdhrubo** [comment]
You are absolutely correct. This is mostly copy and rinse. Please start. I am around to help. This SQL server support is long awaited.

**Comment by lserveriiev** [comment]
@kdhrubo ok, assign the feature [672](https://github.com/kdhrubo/db2rest/issues/672) to me please

**Comment by kdhrubo** [comment]
Unfortunately, Github wont allow me to assign this to you at this time. This is because you are not yet on the contributor list. 
But good news is you have already forked it. 
So break this into multiple small merges. I would suggest you create the new maven module for ms-sqlserver and we can merge. Then github will allow me to assign this to you as you are now a contributor. BTW pls do star the project.

**Comment by lserveriiev** [comment]
@kdhrubo [done](https://github.com/kdhrubo/db2rest/pull/673). Have a look at it, please.

Also want to clean up the existing module if you don't mind.

**Comment by kdhrubo** [comment]
closing this issue as no longer required.
