### ISSUE TITLE
Response with html data

### ISSUE THREAD

**Issue by khanhpd2002** [kdhrubo/db2rest#609]
I have `content` column with datatype is longtext in `postgresql` and store html

When I get `content` with db2rest, it add \\ before each \" 

Example:
Raw data:   <p><strong style=\"color: rgb(230, 0, 0);\">1. Something here</strong></p>

Respond:   <p><strong style=\\\"color: rgb(230, 0, 0);\\\">1. Something here</strong></p>

**Comment by grabdoc** [comment]
@khanhpd2002 - this is done by Jackson serializer to ensure that the JSON is correct. 

If you dump the same in an HTML file it will work. 

```
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
hi

<strong style=\"color: rgb(230, 0, 0);\">1. Something here </strong>

</body>
</html>

 ```

This results in 

<img width="561" alt="image" src="https://github.com/kdhrubo/db2rest/assets/57690705/d80d157c-0dca-4bd2-a53b-206223a2a675">

**Comment by thadguidry** [comment]
But it appears that the escaped double quote should be removed after deserialization, no?  This is more about retaining data quality and accuracy of bytes given to DB2Rest and then handed over to the DB driver.  In this case it seems we retained an extra slash.  Or maybe we added an extra slash \\" prior to serializing? And only one was removed?

**Comment by grabdoc** [comment]
I don't think DB2REST was used for deserialization.

The backslash is added by Jackson to ensure correct JSON.

Try saving it will fail without backslash.
