### ISSUE TITLE
How to Prevent SQL Injection

### ISSUE THREAD

**Issue by tctDarkLight** [kdhrubo/db2rest#658]
How to Prevent SQL Injection

**Comment by kdhrubo** [comment]
@tctDarkLight Currently there is no way to do SQL injection. RSQL is very safe. 

The custom SQL is one area for potential vulnerability. Checks for SQL injection can be added to reject any attempt.

**Comment by tctDarkLight** [comment]
Thank you for your answer!

**Comment by kdhrubo** [comment]
Thanks will close the ticket. Feel free to join our discord group.
