### ISSUE TITLE
Review and change HTTP Response Code for DELETE

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#68]

**Comment by kdhrubo** [comment]
@souravroy - I believe you will or have already changed this. As discussed - now returns 200 and not 204 as you pointed out because of the response body.

**Comment by kdhrubo** [comment]
@souravroy - I believe this issue is fixed now

**Comment by souravroy** [comment]
@kdhrubo This issue was already fixed.
https://github.com/kdhrubo/db2rest/blob/master/src/main/java/com/homihq/db2rest/rest/delete/DeleteRestApi.java#L11

Hence, closing this ticket.
