### ISSUE TITLE
Accept-Profile header is missused

### ISSUE THREAD

**Issue by simasch** [kdhrubo/db2rest#79]
I don't think the Accept-Profile header is an appropriate way to specify the schema.

This is what the Accept-Profile header is intended for:
https://profilenegotiation.github.io/I-D-Accept--Schema/I-D-accept-schema#rfc.section.3

Why not name it DDB-Schema?

**Comment by thadguidry** [comment]
I think Accept-Profile is a perfectly acceptable way for a User Agent to specify a preference for a particular resource.  In this case, a **schema**.
If you read the latest W3C Working Draft available at https://www.w3.org/TR/dx-prof-conneg/
it explains from Lars and Ruben a bit of the history in the Abstract and Sections 1-5.  Essentially, we want clients to negotiate the content provided by servers based on a data profile to which the content conforms.  This is typical in many data serving application stacks.

We could use the http `Prefer` header field but this has a disadvantage as explained already in the draft's section https://www.w3.org/TR/dx-prof-conneg/#using-the-prefer-preference-applied-header-fields-rfc-7240

Happy to continue discussion and hear specific points you might have been alluding to but didn't come across well in your above comment.

Having said the above.  **schema** could certainly just be passed as a parameter just as is typically done in a URI-like string ex. https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html

**Comment by thadguidry** [comment]
Oh and thanks so much @simasch for chiming in and taking a look at the project!

**Comment by simasch** [comment]
Thanks for the clarification. If create another issue #80 because I think the schema will not matter in most cases

**Comment by kdhrubo** [comment]
Closing as a new issue created. #80
