### ISSUE TITLE
How will you handle jOOQ Pro versions?

### ISSUE THREAD

**Issue by simasch** [kdhrubo/db2rest#81]
jOOQ is only free for OSS databases in the latest version. 

How do you plan to handle the pro versions?

**Comment by kdhrubo** [comment]
This is a good point.
Current focus is MySQL, PostgreSQL with OSS. 

May be in future when dust stabilizes, create a version inline with jOOQ Pro.
Oracle already has ORDS and SQLServer is covered with Azure REST data API. So currently Oracle, SQLServer are low priority.

**Comment by simasch** [comment]
To use jOOQ Pro you must be a paying customer. There is no public repo with the jOOQ Pro dependencies.

**Comment by simasch** [comment]
And also keep in mind that only the latest OSS versions are supported by the free version.

**Comment by kdhrubo** [comment]
Great insight. We will switch over from jOOQ to a custom SQL generator. That also derisk from too many 3rd party dependency. jOOQ is great is a risk too and before too much code is written will refactor to remove it gradually.

**Comment by kdhrubo** [comment]
All right finally decided to switch to MyBatis dynamic SQL generator which is very similar to jOOQ. However it does not have licensing concerns, full source available, frequently updated, and extensible. Successfully added it to Insert operation and there is visible performance boost as well. 

https://mybatis.org/mybatis-dynamic-sql/docs/introduction.html

@simasch @thadguidry - please review and will close the ticket.

**Comment by thadguidry** [comment]
Mybatis is well regarded in the industry.

**Comment by simasch** [comment]
MyBatis may be a good choice for what you are doing.

**Comment by kdhrubo** [comment]
So eventually now the code base is free of jOOQ and everything is replaced by Mybatis dynamic SQL generator. Will continue to test going forward.
