### ISSUE TITLE
Support for stored procedure - Postgresql

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/db2rest#89]
Support calling stored procedures/stored functions for postgresql database

End point - /procedure
Method - POST 

The input parameters for the stored procedure call are submitted as JSON 

{ "x": 55 "y": 12 }

Example 

```java

// Create a SimpleJdbcCall object
        SimpleJdbcCall jdbcCall = new SimpleJdbcCall(dataSource)
                .withProcedureName("get_book_by_name")
                .declareParameters(new SqlParameter("p_name", Types.VARCHAR),
                        new SqlOutParameter("o_c_book", Types.OTHER));

        // Create a Map object to hold the input parameters
        Map<String, Object> inParams = new HashMap<>();
        inParams.put("p_name", "The Catcher in the Rye");

        // Call the stored procedure and get the output parameters
        Map<String, Object> outParams = jdbcCall.execute(inParams);

        // Print the output parameters
        System.out.println("o_c_book: " + outParams.get("o_c_book"));
```

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/object/StoredProcedure.html

This class looks a good abstraction as well. 

The output values must be returned as JSON as well.

**Comment by thadguidry** [comment]
Just make sure you setup a test where you can pass `NULL` as an argument.  PostgreSQL supports the **OUT** parameter now. 
 Fully read, at the bottom it shows handling. https://www.migops.com/blog/stored-procedure-out-parameters-in-postgresql-14/

**Comment by souravroy** [comment]
@thadguidry The difference that I noticed is that when we call the stored proc in SQL we need to explicitly set `null` for the OUT parameter, however from the java code (SimpleJdbcCall) it seems that we don't need to set any value for the OUT parameter, I just set the value for IN parameter and the proc returned result successfully

**Comment by souravroy** [comment]
We need to create a separate endpoint for database `function` as well.

**Comment by thadguidry** [comment]
Hi @souravroy if there was a question somewhere in your last comments, I didn't pick it up or deduce it.  Can you reply and form a question if you still have any? Thanks!

**Comment by souravroy** [comment]
Including the PR:
https://github.com/kdhrubo/db2rest/pull/103
