### ISSUE TITLE
REST API versioning

### ISSUE THREAD

**Issue by souravroy** [kdhrubo/db2rest#93]
To implement API versioning. 

The version needs to be upgraded for a major release. The client can continue to use older version of the APIs and they can migrate to newer version of the APIs when they are ready.

If we adapt versioning through URI path then existing API endpoints needs to be refactored to accommodate version details. For e.g. 
`http://localhost:8080/api/v1/actor?select=actor_id,first_name,last_name&filter=first_name=="PENELOPE"&page=0&size=2`

**Comment by thadguidry** [comment]
1. Don't use URL versioning, instead use HTTP headers for content negotiation. `"Accept-Version: V2"`
    - Must Read: https://cloud.google.com/blog/products/api-management/common-misconceptions-about-api-versioning
2. Or just use API Keys? https://json-ld.org/spec/latest/json-ld-api-best-practices/#api-versioning

**Comment by kdhrubo** [comment]
I am not sure if Spring supports versioning via content negotiation. We
have check.

Otherwise version in URL is commonly used and natively supported by
framework URL path handling.

**Comment by thadguidry** [comment]
There's many reasons to avoid using URL for versioning, but it certainly depends on the lifecycle itself.  Which is why I'd suggest for anyone to read the article.  It details when/why you might want to think differently about API versioning strategies.

**Comment by kdhrubo** [comment]
This is widely supported by Spring Boot so we can support based on content negotiation which is a best practice. 

https://www.javaguides.net/2021/04/rest-apis-versioning.html

https://medium.com/@avi.singh.iit01/a-guide-to-api-versioning-in-spring-boot-d564595bba00

https://www.springboottutorial.com/spring-boot-versioning-for-rest-services

**Comment by kdhrubo** [comment]
Will revisit when there is need for API versioning arises based on user adoption. 
Currently APIs are stabilizing slowly.
